package project3_client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.concurrent.atomic.AtomicInteger;
import java.net.Socket;

/**
 * Threaded Client objects send and receive data from the Server.
 */
public class Threaded_Client extends Thread {

    private String host;
    private int port;
    private final static AtomicInteger numFinished = new AtomicInteger(0);
    protected String outputFromServer;
    protected long totalTime;
    private int clientNumber;

    /**
     * @param host Host name from Client args
     * @param port Port number from Client args
     * @param clientNumber Client number generated by Client class
     */
    Threaded_Client(String host, int port, int clientNumber) {
        this.host = host;
        this.port = port;
        this.clientNumber = clientNumber;
    }

    /**
     * Getter method for atomic number client counter
     * @return number of finished client threads
     */
    protected int getNumFinished() {
        return numFinished.get();
    }

    /**
     * Runs each client thread by utilizing a network socket and input/output streams.
     */
    @Override
    public void run() {
        try(
            Socket socket = new Socket(host, port);
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        ) {
            long startTime = System.nanoTime();                 // Record start time
            out.println(clientNumber);                          // Output client number to Server
            outputFromServer = in.readLine();                   // Input String from Server
            totalTime = (System.nanoTime() - startTime) / 1000000; // Record total time
            numFinished.incrementAndGet();                      // Increment the clients processed integer
        }
        catch (IOException ioe) {
            ioe.printStackTrace();
            System.exit(1);
        }
    }
}
